### ISSUE TITLE
Missing command in Mu--Support-Systems/Directory and Hangouts/1 - info and setup.txt

### ISSUE THREAD

**Issue by skewskewskew** [thenomain/Mu--Support-Systems#2]
Code calls for: `&d.sort.elements [v( d.dah )]=name type`

variable `&dah` is never set on the initial set up. Needs to have

`@fo me=&d.dah me=search( name=Directory and Hangouts <dah>)`

added.

**Comment by thenomain** [comment]
Apparently I did this, but forgot to close this issue out.

Githubbots, Close Out!
