### ISSUE TITLE
Bug on first @set BNWW regex line

### ISSUE THREAD

**Issue by ADHdev** [thenomain/Mu--Support-Systems#3]
https://github.com/thenomain/Mu--Support-Systems/blob/master/Brand%20New%20Who%20Where/bnww%20-%2004%20-%20Finger.txt

`@set Brand New Who-Where [v( d.bnww )]/c.finger=regexp`

Should be:

`@set [v( d.bnww )]/c.finger=regex`

**Comment by thenomain** [comment]
Oops, also fixed as per Issue #4
