### ISSUE TITLE
Wonky Command in Aether's Factions

### ISSUE THREAD

**Issue by lmclarke** [thenomain/Mu--Support-Systems#6]
https://github.com/thenomain/Mu--Support-Systems/blob/065401b79d7ab78cdaaf0c9c58044666ea578684/Aether%20Factions.txt#L180

> faction/create Test Group=CodeWiz
> Huh?  (Type "help" for help.)
> 
> faction/create Test Group
> Huh?  (Type "help" for help.)
> 
> faction/create
> <faction> That's not a good name for a faction

**Comment by thenomain** [comment]
Have you tried using an underscore?

This is a very old and very wonky system that needs recreated from the ground up.
