### ISSUE TITLE
MIssing Command - note/setup

### ISSUE THREAD

**Issue by lmclarke** [thenomain/Mu--Support-Systems#7]
https://github.com/thenomain/Mu--Support-Systems/blob/065401b79d7ab78cdaaf0c9c58044666ea578684/Notes%20System.txt#L840

I noticed that note/setup doesn't appear to exist, though it's listed in the helps. It doesn't seem necessary to create an independent note object to use the system - are the help entries out of date, maybe?

**Comment by thenomain** [comment]
Turns out that instead of having a 'notes object', I just put the notes on the character object itself. Reference in help file removed.
