### ISSUE TITLE
USNO weather API is unreliable

### ISSUE THREAD

**Issue by ADHdev** [thenomain/Mu--Support-Systems#8]
https://github.com/thenomain/Mu--Support-Systems/blob/8d34a7ddf4e3660d5044ef488ee34552c6b6c153/Weather/weather.php#L66

My weather.php keeps throwing errors for the astronomy data:

PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed:
+Name or service not known in /home/nola/weather.php on line 68
PHP Warning:
+file_get_contents(https://api.usno.navy.mil/rstt/oneday?ID=TinyMUX&date=today&c
+oords=29.9576213,-90.0731579): failed to open stream: php_network_getaddresses:
+getaddrinfo failed: Name or service not known in /home/nola/weather.php on line
+68
PHP Notice:  Trying to get property 'sundata' of non-object in
+/home/nola/weather.php on line 375
PHP Warning:  Invalid argument supplied for foreach() in /home/nola/weather.php
+on line 376
PHP Notice:  Trying to get property 'moondata' of non-object in
+/home/nola/weather.php on line 384
PHP Warning:  Invalid argument supplied for foreach() in /home/nola/weather.php
+on line 395
PHP Notice:  Undefined variable: sunrise in /home/nola/weather.php on line 404
PHP Notice:  Undefined variable: sunset in /home/nola/weather.php on line 405
PHP Notice:  Trying to get property 'curphase' of non-object in
+/home/nola/weather.php on line 412
PHP Notice:  Trying to get property 'fracillum' of non-object in
+/home/nola/weather.php on line 413

My weather.php $astronomy_string parses out to: https://api.usno.navy.mil/rstt/oneday?ID=TinyMUX&date=today&coords=29.9576213,-90.0731579

Note that that address on most machines returns a DNS error. If you google "usno.navy.mil dns" you'll find a couple of links dating back to 2014 with DNS issues which suggest to me that the error wasn't fixed back then and won't be fixed now.

I'd like to suggest you replace the astronomy info with Darksky's astronomy info, or calculate moon phase programmatically using standard available PHP scripts like https://github.com/solarissmoke/php-moon-phase.

I'm going to look into poking around at this but I figured I'd better create an issue for you to track first in case you've already solved it and just haven't released the fix yet.

**Comment by ADHdev** [comment]
Testing a possible fix now: https://mm.icann.org/pipermail/tz/2019-July/028303.html

Yeah, that's right, I added:

`199.211.133.93  aa.usno.navy.mil        # astronomical data`

to my /etc/hosts file and re-ran `php weather.php`. We'll see whether it keeps working and stops mailing me errors...

**Comment by ADHdev** [comment]
Nope. Errors still occur.

**Comment by thenomain** [comment]
I am aware of this. It comes and goes, and have recently received a mail from USNO saying they're updating things. Until I can find a more reliable way (such as pure code), it'll come and go.

**Comment by thenomain** [comment]
Still looking for solutions. Closing issue for now.
